### ISSUE TITLE
список процедур по алфавиту

### ISSUE THREAD

**Issue by petypen** [nixel2007/vsc-language-1c-bsl#1]
Добрый день.
Можно ли для команды:

> Список процедур и функций текущего файла по нажатию Ctrl-Shift-O

отображать список процедур и функций отсортированный по алфавиту?

**Comment by nixel2007** [comment]
Сходу не могу даже сказать, могу ли я повлиять на этот порядок :) 
Готовых конфигов в плагине нет, возможно есть какие-то настройки сортировки в параметрах редактора, но на вскидку их не помню. 

Если я правильно понимаю, то сейчас сортировка идёт по номеру строки объявления метода?

**Comment by petypen** [comment]
Никита, добрый день. Нашел решение этого вопроса в расширении https://marketplace.visualstudio.com/items?itemName=patrys.vscode-code-outline Очень удобно. Наверное можно тикет закрывать.
вот скриншот https://yadi.sk/i/IV8jq22x3KVY2Y

**Comment by nixel2007** [comment]
Как раз недавно искал что-то подобное :) Спасибо!
